### PR TITLE
Fixes for panic propagation

### LINKED ISSUE #58: Periodic crashes with panic propagation
I have been seeing travis builds fail unreliably in the negative panic tests. I'll try to pin this down at some point.

cc @Amanieu

### PR DESCRIPTION
**Pull request by Amanieu**
The key part is the missing guard in `steal_until`, which was causing the crashes because unwinding would overwrite the job data.

Another issue was that some injected jobs could be left hanging after the thread pool was terminated. This is resolved by aborting all injected jobs on termination.

I also changed the code back to using a trait and just wrapped the mutable values in `UnsafeCell`.

Fixes #58

### CODE REVIEW

**Comment by nikomatsakis** [comment]
:fireworks: I'll take a look soon, sorry...lots going on! :)

File: src/thread_pool.rs [hunk 1]
```diff
@@ -263,13 +268,26 @@ impl WorkerThread {
 
     #[cold]
     pub unsafe fn steal_until(&self, latch: &SpinLatch) {
+        // If another thread stole our job when we panic, we must halt unwinding
+        // until that thread is finished using it.
+        struct PanicGuard<'a>(&'a SpinLatch);
+        impl<'a> Drop for PanicGuard<'a> {
+            fn drop(&mut self) {
+                while !self.0.probe() {
```
Comment (nikomatsakis) [inline src/thread_pool.rs]: Maybe worth writing a helper fn for this, since we also do a similar spin loop in api.rs?

**Comment by nikomatsakis** [comment]
Looks good -- so the problem was a missing block in `steal_until`?

I definitely prefer the trait + unsafe-cell variant.

File: src/thread_pool.rs (hunk 1 above)
Comment (Amanieu) [inline src/thread_pool.rs]: We could use the [scopeguard](https://crates.io/crates/scopeguard) crate which makes panic guards easier to write.

Comment (nikomatsakis) [inline src/thread_pool.rs]: Hmm, perhaps. scopeguard offers `defer!`, which works in this instance, but not the other case, since we wanted the ability to `mem::forget`...

**Comment by nikomatsakis** [comment]
Well, I'll merge this now, we can consider further cleanup later. I'd like to get a fix in for #58.

File: src/thread_pool.rs (hunk 1 above)
Comment (Amanieu) [inline src/thread_pool.rs]: It also allows you to create a guard without the macro, which *does* allow you to `mem::forget` it later.

Comment (Amanieu) [inline src/thread_pool.rs]: The main question is whether this is worth adding an additional dependency.
